const topCities = [
  "Tokyo",
  "Delhi",
  "Shanghai",
  "Sao Paulo",
  "Mumbai",
  "Beijing",
  "Cairo",
  "Mexico City",
  "Osaka",
  "New York City",
  "Chongqing",
  "Istanbul",
  "Karachi",
  "Buenos Aires",
  "Kolkata",
  "Kinshasa",
  "Manila",
  "Tianjin",
  "Rio de Janeiro",
  "Lahore",
  "Guangzhou",
  "Bangalore",
  "Shenzhen",
  "Moscow",
  "Tehran",
  "Jakarta",
  "London",
  "Lima",
  "Bangkok",
  "Chengdu",
  "Nairobi",
  "Hong Kong",
  "Ho Chi Minh City",
  "Hyderabad",
  "Wuhan",
  "Ahmedabad",
  "Baghdad",
  "Paris",
  "Bogota",
  "Lisbon",
  "Riyadh",
  "Singapore",
  "Bucharest",
  "Luanda",
  "Berlin",
  "Kiev",
  "Brisbane",
  "Barcelona",
  "Sydney",
];

console.log(topCities);
